crm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from users.views import SignupView
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings

# Other URL confs up here

# Do not import anything for the handler404,
# or whatnot from the django.conf.urls
# Just list them below

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',auth_views.LoginView.as_view(template_name='auth/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    url(r'^reset/$', auth_views.PasswordResetView.as_view(template_name='auth/password_reset.html', email_template_name='auth/password_reset_email.html', subject_template_name='auth/password_reset_subject.txt'), name='password-reset'),
    url(r'^reset/done/$', auth_views.PasswordResetDoneView.as_view(template_name='auth/password_reset_done.html'), name='password_reset_done'),
    path('reset/(<uidb64>[0-9A-Za-z_\-]+)/(<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/', auth_views.PasswordResetConfirmView.as_view(template_name='auth/password_reset_confirm.html'),  name='password_reset_confirm'),
    url(r'^reset/complete/$', auth_views.PasswordResetCompleteView.as_view(template_name='auth/password_reset_complete.html'), name='password_reset_complete'),
    url(r'^settings/password/$', auth_views.PasswordChangeView.as_view(template_name='auth/password_change.html'),
    name='password_change'),
url(r'^settings/password/done/$', auth_views.PasswordChangeDoneView.as_view(template_name='auth/password_change_done.html'),
    name='password_change_done'),
    path('signup/', SignupView.as_view(), name='signup'),
    path('leads/',  include('leads.urls', namespace="leads")),
    path('categories/', include('categories.urls', namespace="categories")),
    path('sources/',  include('sources.urls', namespace="sources")),
    path('users/',  include('users.urls', namespace="users")),
    path('csvs/',  include('csvs.urls', namespace="csvs")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

leads/urls.py
from django.urls import path
from django.conf.urls import url
from .views import CommentView, LeadCreateView, LeadUpdateView, ModifyView, lead_delete, LeadView, LeadIndexView, SearchResultsView, LeadAdvancedSearch
from django.contrib.auth.decorators import login_required



app_name = "leads"
urlpatterns =[
    path('', login_required(LeadIndexView.as_view()), name='lead-index'),
    path('<int:pk>/update/', login_required(LeadUpdateView.as_view()), name='lead-update'),
    url(r'^create/$', login_required(LeadCreateView.as_view()), name='lead-create'),
    path('<int:pk>/delete/', login_required(lead_delete), name='lead-delete'),
    url(r'^delete/$', login_required(LeadView.as_view()), name='delete-multiple'),
    url(r'^modify/$', login_required(ModifyView.as_view()), name='modify'),
    url(r'^search/$', login_required(SearchResultsView.as_view()), name='search'),
    url(r'^filtering/$', login_required(LeadAdvancedSearch.as_view()), name='advanced-search'),
    path('<int:pk>/comment', (CommentView.as_view()), name='comment'),


    #path('<int:pk>/update/', LeadUpdateView.as_view(), name='lead-update'),
    #path('create/', LeadCreateView.as_view(), name='lead-create'),
    #path('<int:pk>/delete/', lead_delete, name='lead-delete'),
    #path('delete/', LeadView.as_view(), name='delete-multiple'),
    #path('search/', SearchResultsView.as_view(), name='search'),
    #path('searching/', LeadAdvancedSearch.as_view(), name='advanced-search'),
    #path('status/', LeadAdvancedStatus.as_view(), name='status'),
]

leads/models.py
from django.db import models
from categories.models import Category
from sources.models import Source
from users.models import User
from django.shortcuts import reverse

# Create your models here.


class Lead(models.Model):
    
    name = models.CharField(max_length=50)
    phone = models.CharField(max_length=30)
    email = models.CharField(max_length=30)
    source = models.ForeignKey(Source, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, default='NEW')
    task = models.DateTimeField(blank=True, null=True)
    user = models.ForeignKey(User, default='misen', on_delete=models.CASCADE)
    deposit = models.BooleanField(default=False)
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.name




class Comment(models.Model):
    lead = models.ForeignKey(Lead, related_name='comments', on_delete=models.CASCADE)
    user = models.ForeignKey(User, editable=False, on_delete=models.CASCADE)
    body = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Comment: {self.lead}-{self.user}"

leads/forms.py
from django.db.models import fields
from django.db.models.fields import DateTimeField
from .models import Comment, Lead, User, Category
from django import forms
from django.forms import Textarea
from flatpickr import DateTimePickerInput


class LeadModelForm(forms.ModelForm):
  class Meta:
    model = Lead
    fields = (
        'name',
        'phone',
        'email',
        'source',
        'category',
        'task',
        'user',
        'deposit'
    )
    widgets = {
        'task': DateTimePickerInput(attrs={'placeholder':'Select Date/Time.'}),
    }

  
class LeadModifyForm(forms.ModelForm):
  class Meta:
    model = Lead
    fields = (
      'user',
      'category'
    )



class CommentForm(forms.ModelForm):
  class Meta:
    model = Comment
    fields = ('body',)

    widgets = {
      'body': Textarea(attrs={'cols': 14, 'rows': 2}),
    }

class SearchForm(forms.ModelForm):
  class Meta:
        fields = (
        'name',
        'phone',
        'email',
        'source',
        'category',
        'task',
        'user',
        'deposit',
        'created_at'
        )
        widgets = {
            'task': DateTimePickerInput(attrs={'placeholder':'Select Date/Time.'}),
            'created_at': DateTimePickerInput(attrs={'placeholder':'Select Date/Time.'}),
        }

leads/views.py
from django.shortcuts import render, reverse, redirect
from django.views import generic
from .forms import LeadModelForm, LeadModifyForm, CommentForm
from .models import Comment, Lead
from django.db.models import Q
from .filters import LeadFilter
from django_filters.views import FilterView, object_filter
from users.views import staff
from django.core.exceptions import PermissionDenied
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


# Create your views here.


class LeadCreateView(staff, generic.CreateView):
    model = Lead
    template_name = "leads/lead_create.html"
    form_class = LeadModelForm

    def get_success_url(self):
        return reverse("leads:lead-index")


class LeadUpdateView(generic.UpdateView):
    model = Lead
    template_name = "leads/lead_update.html"
    form_class = LeadModelForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['commentform'] = CommentForm()
        return context

    def get_success_url(self):
        return reverse("leads:lead-index")


class LeadIndexView(generic.ListView):
    model = Lead
    ordering = ['-updated_at']
    template_name = 'leads/lead_index.html'
    paginate_by = 100

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        context['form'] = LeadModifyForm()
        return context


def lead_delete(request, pk):
    lead = Lead.objects.get(id=pk)
    if request.user.is_superuser:
        lead.delete()
    else:
        raise PermissionDenied("Access forbidden 403. Are you root?")
    return redirect("/leads")


class LeadView(staff, generic.View):
    def post(self, request, *args, **kwargs):
        if request.method == "POST":
            lead_ids = request.POST.getlist('id[]')
            for id in lead_ids:
                lead = Lead.objects.get(pk=id)
                lead.delete()
            return redirect("/leads")


class ModifyView(staff, generic.View):
    def post(self, request):
        lead_list = []
        if request.method == "POST":
            form = LeadModifyForm(request.POST)
            lead_ids = request.POST.getlist('id[]')
            for id in lead_ids:
                lead = Lead.objects.get(pk=id)
                if form.is_valid():
                    user = form.cleaned_data['user']
                    category = form.cleaned_data['category']
                    lead.user = user
                    lead.category = category
                lead_list.append(lead)
        Lead.objects.bulk_update(lead_list, ['category', 'user'])
        return redirect("leads:lead-index")


class SearchResultsView(generic.ListView):
    model = Lead
    template_name = 'leads/lead_index.html'
    paginate_by = 100
    ordering = ['-updated_at']

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        context['form'] = LeadModifyForm()
        return context

    def get_queryset(self):  # new
        query = self.request.GET.get('q')
        if query:
            q_list = Lead.objects.filter(
                Q(name__icontains=query) | Q(phone__icontains=query) | Q(id__icontains=query) |
                Q(email__icontains=query) | Q(category__category__icontains=query) |
                Q(source__source__icontains=query) | Q(created_at__icontains=query) | Q(
                    user__username__icontains=query) | Q(id__icontains=query) | Q(task__icontains=query)
            ).order_by('-updated_at')
            return q_list
        return Lead.objects.all().order_by('-updated_at')


class LeadAdvancedSearch(FilterView):
    paginate_by = 100
    filterset_class = LeadFilter
    template_name = 'leads/search_index.html'
    queryset = Lead.objects.all().order_by('-updated_at')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = LeadModifyForm()
        return context




class CommentView(generic.CreateView):
    model = Comment
    form_class = CommentForm
    template_name = 'leads/lead_comment.html'

    def form_valid(self, form):
        form.instance.lead_id = self.kwargs['pk']
        form.instance.user_id = self.request.user.id
        return super().form_valid(form)

    def get_success_url(self, **kwargs):
        pk = self.kwargs.get('pk')
        lead = Lead.objects.get(id=pk)
        return reverse("leads:lead-update", kwargs={'pk': lead.pk})

leads/templates/leads/lead_comment.html
{% extends 'base.html' %}
{% load tailwind_filters %}
{% block content %}
{{form.media}}
<title>
    {% block title %}
    {% endblock title %}
  </title>
  <div class="well">
  <div class="row justify-content-center grid">
      <div class="redbull text-muted text-center">
          <h3 class="card-title">Create a new comment.</b> </h3>
          </div>
        </div>
        <form action="" method="post">
          {% csrf_token %}
          {{form|crispy}}
        </div>
        <br>
          <div class="text-muted text-center">
            <button type="submit" class="btn btn-primary btn-block"><span class="fa fa-hdd" aria-hidden="true"></span> Create</button>
          </form>
          <h1 style="margin-top: 10px;"><a href="/leads"class="btn btn-danger btn-block"><span class="fa fa-undo" aria-hidden="true"></span> Back</a></h1>
          </div>
    </div>
</div>
</div>
{% endblock content %}

leads/templates/leads/lead_create.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block content %}
{{form.media}}
<title>
    {% block title %}
      create lead
    {% endblock title %}
  </title>
        <form action="" method="post">
          <div class="row">
          {% csrf_token %}
          <div class="form-group col-sm-4 col-md-6">
            {{ form.name.label_tag }}*
            {% render_field form.name class="form-control" %}
          </div>
          <div class="form-group col-sm-4 col-md-6">
            {{ form.category.label_tag }}
            {% render_field form.category class="form-control" %}
          </div>
          <div class="form-group col-sm-4 col-md-6">
            {{ form.phone.label_tag }}*
            {% render_field form.phone class="form-control" %}
          </div>
          <div class="form-group col-sm-4 col-md-6">
            {{ form.source.label_tag }}*
            {% render_field form.source class="form-control" %}
          </div>
          <div class="form-group col-sm-4 col-md-6">
            {{ form.email.label_tag }}*
            {% render_field form.email class="form-control" %}
          </div>
            <div class="form-group col-sm-4 col-md-6">
              {{ form.task.label_tag }}
              {% render_field form.task class="form-control" %}
            </div>
            <div class="form-group col-sm-4 col-md-6">
              {{ form.user.label_tag }}
              {% render_field form.user class="form-control" %}
            </div>
            <div class="form-group col-sm-4 col-md-6">
              {{ form.comment.label_tag }}
              {% render_field form.comment class="form-control" %}
            </div>
        </div>
        <br>
          <div class="text-muted text-center">
            <button type="submit" class="btn btn-primary btn-block"><span class="fa fa-hdd" aria-hidden="true"></span> Create</button>
          </form>
          <h1 style="margin-top: 10px;"><a href="/leads"class="btn btn-danger btn-block"><span class="fa fa-undo" aria-hidden="true"></span> Back</a></h1>
          </div>
        </div>
{% endblock content %}

leads/templates/leads/lead_index.html
{%extends 'base.html'%}
{% load tailwind_filters %}
{% load widget_tweaks %}
<title>
	{% block title %}
	  leads
	{% endblock title %}
  </title>
{%block content%}
<br><br>
<table id="misen" class="table table-bordered table-hover nowrap table-sm" cellspacing="0" style="width:100%">
    {% csrf_token %}
	<thead class="thead-dark">
		<tr>
			<th class="text-center">#</th>
            {% if request.user.is_staff %}
            <th class="text-center"><input type="checkbox" name="" id="site_select_all"></th>
            {% endif %}
			<th class="text-center">Name</th>
			<th class="text-center">Phone</th>
			<th class="text-center">Data Creation</th>
			<th class="text-center">Source</th>
			<th class="text-center">Category</th>
            {% if request.user.is_staff %}
            <th class="text-center">User</th>
			<th class="text-center">Action</th>
            {% endif %}
		</tr>
	</thead>
	<tbody>
		{% for lead in object_list %}
        {% if request.user.is_staff or lead.user == request.user %}
		<tr id="{{lead.id}}">
			<td class="text-center">{{lead.id}}</td>
            {% if request.user.is_staff %}
            <td class="text-center"><input type="checkbox" name="sel" id="delete_lead" value="{{lead.id}}"></td>
            {% endif %}
			<td class="text-center"><a href="{% url 'leads:lead-update' lead.pk %}">{{lead.name}}</a></td>
			<td class="text-center">{{lead.phone}}</td>
			<td class="text-center">{{lead.created_at|date:'Y-m-d'}}</td>
			<td class="text-center">{{lead.source}}</td>
			<td class="text-center">{{lead.category}}</td>
            {% if request.user.is_staff %}
            <td class="text-center">{{lead.user}}</td>
			<td class="text-center">
				<a href="{% url 'leads:lead-update' lead.pk %}"><i class="fas fa-edit text-primary"></i></a>
				<a href="{% url 'leads:lead-delete' lead.pk %}" onclick="return confirm('Are you sure to delete this Lead?');"><i class="fas fa-trash-alt text-danger"></i></a>
			</td>
            {% endif %}
		</tr>
        {% endif %}
		{% endfor %}
	</tbody>
</table>
<div class="pagination justify-content-center">
  <span class="step-links">
      {% if page_obj.has_previous %}
          <a href="?page=1">&laquo; first</a>
          <a href="?page={{ page_obj.previous_page_number }}">previous</a>
      {% endif %}

      <span class="current">
          Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
      </span>

      {% if page_obj.has_next %}
          <a href="?page={{ page_obj.next_page_number }}">next</a>
          <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
      {% endif %}
  </span>
</div>
<br><br>
{% if request.user.is_staff %}
  
<div class="d-flex flex-items-stretch ml-n2 mr-n2 flex-wrap">
                
    <div class="col-12 col-md-6 d-flex flex-column px-2">
      <div class="Box rounded-2 d-flex flex-column overflow-hidden width-full flex-auto mb-4">
        <div class="d-flex flex-justify-between px-4 pt-3 pb-4" style="min-height: 136px">
          <div class="pr-4">
            <h4 class="mb-1 lh-condensed">Bulk Delete</h4>
  
            <p class="color-text-tertiary f6">
              By
                GitCrm Actions
            </p>
  
            <p class="color-text-tertiary f6 mb-2">
              Delete multiple leads all at once.
            </p>
            <button id="delete_all" class="btn d-none d-lg-inline-block btn-block" style="background-color: crimson; color: white;">Bulk Delete</button>
          </div>
          <div>
            <div class="CircleBadge CircleBadge--small" style="color: #3572A5; background-color: var(--color-scale-white);">
                <img class="CircleBadge-icon" src="data:image/svg+xml;base64,PHN2ZyBmaWxsPSJub25lIiBoZWlnaHQ9IjQ4IiB3aWR0aD0iNDgiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PGcgZmlsbD0iIzJiYTk3NyI+PHBhdGggZD0iTTIxLjA5MyAwaDcuOTMzdjM2LjAyMmMtNC4wNjQuNzYyLTcuMDU1IDEuMDYxLTEwLjI5MiAxLjA2MUM5LjA0NCAzNy4wNzMgNCAzMi43ODUgNCAyNC41NWMwLTcuOTM2IDUuMzUtMTMuMDg2IDEzLjY0MS0xMy4wODYgMS4yODcgMCAyLjI2Ny4xIDMuNDUyLjR6bS4yNzggMTguMzU1Yy0uOTMtLjMtMS42OTUtLjQtMi42NzYtLjQtNC4wMTIgMC02LjMzIDIuNDI0LTYuMzMgNi42NzMgMCA0LjEzNyAyLjIxNiA2LjQyMiA2LjI4IDYuNDIyLjg3OCAwIDEuNTkyLS4wNSAyLjcyNi0uMnoiLz48cGF0aCBkPSJNNDIgMTIuNDN2MTguMDM1YzAgNi4yMTItLjQ3IDkuMTk5LTEuODQ4IDExLjc3NC0xLjI4NyAyLjQ3Ni0yLjk4MiA0LjAzNy02LjQ4NCA1Ljc2MWwtNy4zNjItMy40MzdjMy41MDMtMS42MTIgNS4xOTgtMy4wMzcgNi4yOC01LjIxMSAxLjEzMy0yLjIyMyAxLjQ5LTQuNzk4IDEuNDktMTEuNTcyVjEyLjQzek0zMy4yNzcgMGg3LjkzNHY3Ljk4NmgtNy45MzR6Ii8+PC9nPjwvc3ZnPg==" alt="Django logo">
          </div>
          </div>
        </div>
        <div class="d-flex flex-column flex-auto flex-justify-end">
            <code class="color-text-tertiary text-mono d-block mb-3 flex-auto px-4">
                Be careful this action can never be undone.<br>
                If you click bulk delete they will permanently be destroyed on the database.<br>
                Keep track of everything happening in your project and see exactly what’s changed since the last time you looked.<br>
                When deleting leads instead archive them to some dummy user, you can choose to reuse these leads later stored using Git LFS in the database.<br>
            </code>
          <div class="d-flex flex-justify-between flex-items-center pt-2 pb-3 px-4">
            <a href="#" class="d-flex flex-items-center text-small Link--muted no-wrap overflow-hidden">
              <svg aria-hidden="true" height="16" viewBox="0 0 16 16" version="1.1" width="16" data-view-component="true" class="octicon octicon-repo flex-shrink-0 mr-1">
      <path fill-rule="evenodd" d="M2 2.5A2.5 2.5 0 014.5 0h8.75a.75.75 0 01.75.75v12.5a.75.75 0 01-.75.75h-2.5a.75.75 0 110-1.5h1.75v-2h-8a1 1 0 00-.714 1.7.75.75 0 01-1.072 1.05A2.495 2.495 0 012 11.5v-9zm10.5-1V9h-8c-.356 0-.694.074-1 .208V2.5a1 1 0 011-1h8zM5 12.25v3.25a.25.25 0 00.4.2l1.45-1.087a.25.25 0 01.3 0L8.6 15.7a.25.25 0 00.4-.2v-3.25a.25.25 0 00-.25-.25h-3.5a.25.25 0 00-.25.25z"></path>
  </svg>
              <span class="mr-1 width-full overflow-hidden" style="text-overflow: ellipsis;">
                actions/starter-workflows
              </span>
            </a>
            <div class="d-flex flex-items-center flex-auto flex-justify-end no-wrap overflow-hidden">
                  <span class="color-text-tertiary text-small overflow-hidden width-full text-right" style="text-overflow: ellipsis;">
                    Django
                  </span>
              <span class="repo-language-color ml-2 top-0 flex-shrink-0" style="background-color: #e34c26"></span>
            </div>
          </div>
        </div>
      </div>
    </div>
  
    <div class="col-12 col-md-6 d-flex flex-column px-2">
      <div class="Box rounded-2 d-flex flex-column overflow-hidden width-full flex-auto mb-4">
        <div class="d-flex flex-justify-between px-4 pt-3 pb-4" style="min-height: 136px">
          <div class="pr-4">
            <h4 class="mb-1 lh-condensed">Bulk Update</h4>
  
            <p class="color-text-tertiary f6">
              By
                GitCrm Actions
            </p>
  
            <p class="color-text-tertiary f6 mb-2">
              Update multiple leads details all at once.
            </p>
            <form action="{% url 'leads:modify' %}" method="post" id="form1">
                {% csrf_token %}
                {{form|crispy}}
            <button id="assign" type="submit" class="btn d-none d-lg-inline-block btn-block btn-primary">Update Leads</button>
            </form>
          </div>
          <div>
            <div class="CircleBadge CircleBadge--small" style="color: #3572A5; background-color: var(--color-scale-white);">
                  <img class="CircleBadge-icon" src="data:image/svg+xml;base64,PHN2ZyBmaWxsPSJub25lIiBoZWlnaHQ9IjQ4IiB3aWR0aD0iNDgiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PGcgZmlsbD0iIzJiYTk3NyI+PHBhdGggZD0iTTIxLjA5MyAwaDcuOTMzdjM2LjAyMmMtNC4wNjQuNzYyLTcuMDU1IDEuMDYxLTEwLjI5MiAxLjA2MUM5LjA0NCAzNy4wNzMgNCAzMi43ODUgNCAyNC41NWMwLTcuOTM2IDUuMzUtMTMuMDg2IDEzLjY0MS0xMy4wODYgMS4yODcgMCAyLjI2Ny4xIDMuNDUyLjR6bS4yNzggMTguMzU1Yy0uOTMtLjMtMS42OTUtLjQtMi42NzYtLjQtNC4wMTIgMC02LjMzIDIuNDI0LTYuMzMgNi42NzMgMCA0LjEzNyAyLjIxNiA2LjQyMiA2LjI4IDYuNDIyLjg3OCAwIDEuNTkyLS4wNSAyLjcyNi0uMnoiLz48cGF0aCBkPSJNNDIgMTIuNDN2MTguMDM1YzAgNi4yMTItLjQ3IDkuMTk5LTEuODQ4IDExLjc3NC0xLjI4NyAyLjQ3Ni0yLjk4MiA0LjAzNy02LjQ4NCA1Ljc2MWwtNy4zNjItMy40MzdjMy41MDMtMS42MTIgNS4xOTgtMy4wMzcgNi4yOC01LjIxMSAxLjEzMy0yLjIyMyAxLjQ5LTQuNzk4IDEuNDktMTEuNTcyVjEyLjQzek0zMy4yNzcgMGg3LjkzNHY3Ljk4NmgtNy45MzR6Ii8+PC9nPjwvc3ZnPg==" alt="Django logo">
            </div>
          </div>
        </div>
        <div class="d-flex flex-column flex-auto flex-justify-end">
          <div class="d-flex flex-justify-between flex-items-center pt-2 pb-3 px-4">
            <a href="#" class="d-flex flex-items-center text-small Link--muted no-wrap overflow-hidden">
              <svg aria-hidden="true" height="16" viewBox="0 0 16 16" version="1.1" width="16" data-view-component="true" class="octicon octicon-repo flex-shrink-0 mr-1">
      <path fill-rule="evenodd" d="M2 2.5A2.5 2.5 0 014.5 0h8.75a.75.75 0 01.75.75v12.5a.75.75 0 01-.75.75h-2.5a.75.75 0 110-1.5h1.75v-2h-8a1 1 0 00-.714 1.7.75.75 0 01-1.072 1.05A2.495 2.495 0 012 11.5v-9zm10.5-1V9h-8c-.356 0-.694.074-1 .208V2.5a1 1 0 011-1h8zM5 12.25v3.25a.25.25 0 00.4.2l1.45-1.087a.25.25 0 01.3 0L8.6 15.7a.25.25 0 00.4-.2v-3.25a.25.25 0 00-.25-.25h-3.5a.25.25 0 00-.25.25z"></path>
  </svg>
              <span class="mr-1 width-full overflow-hidden" style="text-overflow: ellipsis;">
                actions/starter-workflows
              </span>
            </a>
            <div class="d-flex flex-items-center flex-auto flex-justify-end no-wrap overflow-hidden">
                  <span class="color-text-tertiary text-small overflow-hidden width-full text-right" style="text-overflow: ellipsis;">
                    Python
                  </span>
              <span class="repo-language-color ml-2 top-0 flex-shrink-0" style="background-color: #3572A5"></span>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

{% endif %}
<script>
	    function get_Selected_id() {
            var searchIDs = $("input[name=sel]:checked").map(function(){
                return $(this).val();
            }).get();
            return searchIDs;
        }

        $(document).ready(function() {
            var table = $('#misen').DataTable({
                "paging": true,
                "aLengthMenu": [[10, 25, 50, 100,], [10, 25, 50, 100,]],
                "iDisplayLength": 50,
                "searching": false,
                "responsive": true,
                "ordering":true,
                "order": []
            });
            // Handle click on "Select all" control
            $('#site_select_all').on('click', function(){
                // Check/uncheck all checkboxes in the table
                var rows = table.rows({ 'search': 'applied' }).nodes();
                $('input[type="checkbox"]', rows).prop('checked', this.checked);
            });

        $("#assign").click(function(event){
                event.preventDefault();
                    var id = get_Selected_id();
                    var csrf = $('input[name=csrfmiddlewaretoken').val();
                    var user = document.getElementById("id_user").value;
                    var category = document.getElementById('id_category').value;
                    if (id!='') {
                        /*$('#delete_leads_ids').eq(0).val(leads_ids);
                        $('#delete_multiple_form').submit();*/
                        $.ajax({
                            url: "{%url 'leads:modify' %}",
                            method: "POST",
                            data: {
                                id,
                                csrfmiddlewaretoken:csrf,
                                user, category
                            },
                            success:function(response){
                                for(var i=0; i<id.length; i++){
                                    $('tr#'+id[i]+'').css('background-color', '#ccc');
                                    $('tr#'+id[i]+'').fadeOut('slow');
                                }
                                window.location.href = ".";
                            }
                        })

                    } else {
                        return confirm("No leads selected");
                    }
                return false;
            });

            $('#delete_all').click(function(event){
          event.preventDefault();
          if(confirm("Are you sure to delete selected?")){
              var id = get_Selected_id();
              var csrf = $('input[name=csrfmiddlewaretoken').val();
              if(id!=''){
                  $.ajax({
                      url: "{%url 'leads:delete-multiple' %}",
                      method: "POST",
                      data: {
                          id,
                          csrfmiddlewaretoken:csrf,
                      },
                      success:function(response){
                          for(var i=0; i<id.length; i++){
                              $('tr#'+id[i]+'').css('background-color', '#ccc');
                              $('tr#'+id[i]+'').fadeOut('slow');
                          }
                          window.location.href = ".";
                      }
                  })
              }
              else{
                  return confirm("No leads selected");
              }
          }
          return false;
        });
    });
</script>
{%endblock content%}