crm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from users.views import SignupView
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings

# Other URL confs up here

# Do not import anything for the handler404,
# or whatnot from the django.conf.urls
# Just list them below

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',auth_views.LoginView.as_view(template_name='auth/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    url(r'^reset/$', auth_views.PasswordResetView.as_view(template_name='auth/password_reset.html', email_template_name='auth/password_reset_email.html', subject_template_name='auth/password_reset_subject.txt'), name='password-reset'),
    url(r'^reset/done/$', auth_views.PasswordResetDoneView.as_view(template_name='auth/password_reset_done.html'), name='password_reset_done'),
    path('reset/(<uidb64>[0-9A-Za-z_\-]+)/(<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/', auth_views.PasswordResetConfirmView.as_view(template_name='auth/password_reset_confirm.html'),  name='password_reset_confirm'),
    url(r'^reset/complete/$', auth_views.PasswordResetCompleteView.as_view(template_name='auth/password_reset_complete.html'), name='password_reset_complete'),
    url(r'^settings/password/$', auth_views.PasswordChangeView.as_view(template_name='auth/password_change.html'),
    name='password_change'),
url(r'^settings/password/done/$', auth_views.PasswordChangeDoneView.as_view(template_name='auth/password_change_done.html'),
    name='password_change_done'),
    path('signup/', SignupView.as_view(), name='signup'),
    path('leads/',  include('leads.urls', namespace="leads")),
    path('categories/', include('categories.urls', namespace="categories")),
    path('sources/',  include('sources.urls', namespace="sources")),
    path('users/',  include('users.urls', namespace="users")),
    path('csvs/',  include('csvs.urls', namespace="csvs")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import UserIndexView, UserCreateAsAdminView, UserPasswordView, UserUpdateView, user_delete


app_name = 'users'

urlpatterns =[
    path('', login_required(UserIndexView.as_view()), name='user-index'),
    path('<int:pk>/update/', login_required(UserUpdateView.as_view()), name='user-update'),
    path('<int:pk>/password/', login_required(UserPasswordView.as_view()), name='user-password'),
    path('create/', login_required(UserCreateAsAdminView.as_view()), name='user-create'),
    path('<int:pk>/delete/', login_required(user_delete), name='user-delete'),
]

users/models.py
from django.contrib.auth import get_user_model

# Create your models here.

User = get_user_model()

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignUpForm(UserCreationForm):
    email = forms.CharField(max_length=254, required=True, widget=forms.EmailInput())
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')

users/views.py
from django.contrib.auth.forms import UserChangeForm
from django.shortcuts import reverse, redirect
from django.views import generic

from leads.models import Lead
from .models import User
from .forms import SignUpForm
from django.core.exceptions import PermissionDenied
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin



class sudo(LoginRequiredMixin, UserPassesTestMixin):
    def test_func(self):
        if not self.request.user.is_superuser:
         raise PermissionDenied("Access forbidden 403. Are you root?")
        else:
            return self.request.user.is_superuser


class staff(LoginRequiredMixin, UserPassesTestMixin):
    def test_func(self):
        if not self.request.user.is_staff:
         raise PermissionDenied("Restricted action. Staff members only.")
        else:
             return self.request.user.is_staff


class SignupView(generic.CreateView):
    model = User
    template_name = "auth/signup.html"
    form_class = SignUpForm

    def get_success_url(self):
       return reverse("login")

class UserCreateAsAdminView(sudo, generic.CreateView):
    model = User
    template_name = "users/user_create.html"
    form_class = SignUpForm

    def get_success_url(self):
       return reverse("users:user-index")

class UserPasswordView(sudo, generic.UpdateView):
    model = User
    template_name = "users/user_password.html"
    form_class = SignUpForm

    def get_success_url(self):
     return reverse("users:user-index")

class UserUpdateView(sudo, generic.UpdateView):
   model = User
   template_name = "users/user_update.html"
   form_class = UserChangeForm
    
   def get_success_url(self):
     return reverse("users:user-index")


class UserIndexView(sudo, generic.ListView):
   queryset = User.objects.order_by('id')
   paginate_by = 100
   template_name = "users/user_index.html"

def user_delete(request, pk):
    user = User.objects.get(id=pk)
    if request.user.is_superuser:
     user.delete()
    else:
        raise PermissionDenied("Access forbidden 403. Are you root?")
    return redirect("/users")

users/templates/users/user_create.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block content %}
{{form.media}}
<title>
    {% block title %}
      create a new #assign_users
    {% endblock title %}
  </title>
        <form action="" method="post">
          <div class="row">
          {% csrf_token %}
          <div class="form-group col-sm-4 col-md-6">
            {{ form.username.label_tag }}*
            {% render_field form.username class="form-control" %}
          </div>
          <div class="form-group col-sm-4 col-md-6">
            {{ form.email.label_tag }}*
            {% render_field form.email class="form-control" %}
          </div>
          <div class="form-group col-sm-4 col-md-6">
            {{ form.first_name.label_tag }}*
            {% render_field form.first_name class="form-control" %}
          </div>
          <div class="form-group col-sm-4 col-md-6">
            {{ form.last_name.label_tag }}*
            {% render_field form.last_name class="form-control" %}
          </div>
          <div class="form-group col-sm-4 col-md-6">
            {{ form.email.label_tag }}*
            {% render_field form.email class="form-control" %}
          </div>
            <div class="form-group col-sm-4 col-md-6">
              {{ form.password1.label_tag }}*
              {% render_field form.password1 class="form-control" %}
            </div>
            <div class="form-group col-sm-4 col-md-6">
              {{ form.password2.label_tag }}*
              {% render_field form.password2 class="form-control" %}
            </div>
        </div>
        <br>
          <div class="text-muted text-center">
            <button type="submit" class="btn btn-primary btn-block"><span class="fa fa-hdd" aria-hidden="true"></span> Create</button>
          </form>
          <h1 style="margin-top: 10px;"><a href="/leads"class="btn btn-danger btn-block"><span class="fa fa-undo" aria-hidden="true"></span> Back</a></h1>
          </div>
        </div>
{% endblock content %}

users/templates/users/user_index.html
{%extends 'base.html'%}
<title>
	{% block title %}
	  users
	{% endblock title %}
  </title>
  <body>
{%block content%}
<br><br><br>
<table id="users" class="table table-bordered nowrap table-sm" cellspacing="0" style="width:100%">
    {% csrf_token %}
	<thead class="thead-dark">
		<tr>
			<th class="text-center">#</th>
			<th class="text-center">Username</th>
			<th class="text-center">Date Joined</th>
			<th class="text-center">Email</th>
			<th class="text-center">Is Active?</th>
			<th class="text-center">Is Staff?</th>
			<th class="text-center">Is Admin?</th>
			<th class="text-center">Action</th>
		</tr>
	</thead>
	<tbody>
		{% for user in object_list %}
		<tr id="{{lead.id}}">
			<td class="text-center">{{user.id}}</td>
			<td class="text-center"><a href="{% url 'users:user-password' user.pk %}">{{user.username}}</a></td>
			<td class="text-center">{{user.date_joined|date:'Y-m-d'}}</td>
			<td class="text-center">{{user.email}}</td>
			<td class="text-center">{{user.is_active}}</td>
			<td class="text-center">{{user.is_staff}}</td>
			<td class="text-center">{{user.is_superuser}}</td>
			<td class="text-center">
				<a href="{% url 'users:user-update' user.pk %}"><i class="fas fa-edit text-primary"></i></a>
				<a href="{% url 'users:user-delete' user.pk %}" onclick="return confirm('Are you sure to delete this User?');"><i class="fas fa-trash-alt text-danger"></i></a>
			</td>
		</tr>
		{% endfor %}
	</tbody>
</table>
{% if is_paginated %}
<nav aria-label="Page navigation example">
<ul class="pagination justify-content-center pagination-circle">
 {% if page_obj.has_previous %}
  <li class="page-item"><a class="page-link text-secondary" href="?page={{ page_obj.previous_page_number }}"><i class="fas fa-arrow-left text-dark"></i> Previous</a></li>
{% else %}
  <li class="page-item"><a><span class="page-link text-secondary">&laquo;</span></a></li>
{% endif %}
{% for i in paginator.page_range %}
  {% if page_obj.number == i %}
  <li class="active page-item text-secondary"><span class="page-link">{{ i }}</span></li>
  {% else %}
  <li class="page-item"><a class="page-link text-dark" href="?page={{ i }}">{{ i }}</a></li>
  {% endif %}
{% endfor %}
{% if page_obj.has_next %}
  <li class="page-item"><a class="page-link text-secondary" href="?page={{ page_obj.next_page_number }}">Next <i class="fas fa-arrow-right text-dark"></i></a></li>
{% else %}
  <li class="page-item"><span class="page-link text-secondary">&raquo;</span></li>
{% endif %}
</ul>
</nav>
{% endif %}
<br><br>
<script>
    $(document).ready(function(){
        var table = $('#users').DataTable({
            "paging":true,
            "aLengthMenu":[[10,25,50,100],[10,25,50,100]],
            "iDisplayLength":25,
            "searching":true,
            "responsive":true,
            "order": []
        });
	});
</script>
{%endblock content%}
</body>

users/templates/users/user_password.html
{% extends "base.html" %}
{% load tailwind_filters %}
{{form.media}}
{% block title %}
  update {{user.username}}
{% endblock title %}
{% block content %}
<br>
  <div class="row justify-content-center">
    <div class="col-lg-10 col-md-10 col-sm-10">
          <h3 class="card-title">Update credentials for <b class="text-info">{{user.first_name}} {{user.last_name}}</b>.</h3>
          <form method="post" novalidate>
            {% csrf_token %}
            {{form|crispy}}
        <button type="submit" class="btn btn-primary col-lg-6"><span class="fa fa-hdd" aria-hidden="true"></span> Submit</button>
      </form>
      <h1 style="margin-top: 10px;"><a href="/users"class="btn btn-danger col-lg-6"><span class="fa fa-undo" aria-hidden="true"></span> Back</a></h1>
      </div>
</div>
{% endblock content %}

users/templates/users/user_update.html
{% extends "base.html" %}
{% load tailwind_filters %}
{{form.media}}
{% block title %}
  update {{user.username}}
{% endblock title %}
{% block content %}
<br>
  <div class="row justify-content-center">
    <div class="col-lg-10 col-md-10 col-sm-10">
          <h3 class="card-title">Update properties and permissions for <b class="text-info">{{user.first_name}} {{user.last_name}}</b>.</h3>
          <form method="post" novalidate>
            {% csrf_token %}
            {{form|crispy}}
        <button type="submit" class="btn btn-primary col-lg-6"><span class="fa fa-hdd" aria-hidden="true"></span> Submit</button>
      </form>
      <h1 style="margin-top: 10px;"><a href="/users"class="btn btn-danger col-lg-6"><span class="fa fa-undo" aria-hidden="true"></span> Back</a></h1>
    </div>
</div>
{% endblock content %}