categories/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import CategoryCreateView, CategoryUpdateView, MixViewCategory, category_delete


app_name = 'categories'

urlpatterns =[
    path('', login_required(MixViewCategory.as_view()), name='category-index'),
    path('<int:pk>/update/', login_required(CategoryUpdateView.as_view()), name='category-update'),
    path('create/', login_required(CategoryCreateView.as_view()), name='category-create'),
    path('<int:pk>/delete/', login_required(category_delete), name='category-delete'),
]

crm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from users.views import SignupView
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings

# Other URL confs up here

# Do not import anything for the handler404,
# or whatnot from the django.conf.urls
# Just list them below

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',auth_views.LoginView.as_view(template_name='auth/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    url(r'^reset/$', auth_views.PasswordResetView.as_view(template_name='auth/password_reset.html', email_template_name='auth/password_reset_email.html', subject_template_name='auth/password_reset_subject.txt'), name='password-reset'),
    url(r'^reset/done/$', auth_views.PasswordResetDoneView.as_view(template_name='auth/password_reset_done.html'), name='password_reset_done'),
    path('reset/(<uidb64>[0-9A-Za-z_\-]+)/(<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/', auth_views.PasswordResetConfirmView.as_view(template_name='auth/password_reset_confirm.html'),  name='password_reset_confirm'),
    url(r'^reset/complete/$', auth_views.PasswordResetCompleteView.as_view(template_name='auth/password_reset_complete.html'), name='password_reset_complete'),
    url(r'^settings/password/$', auth_views.PasswordChangeView.as_view(template_name='auth/password_change.html'),
    name='password_change'),
url(r'^settings/password/done/$', auth_views.PasswordChangeDoneView.as_view(template_name='auth/password_change_done.html'),
    name='password_change_done'),
    path('signup/', SignupView.as_view(), name='signup'),
    path('leads/',  include('leads.urls', namespace="leads")),
    path('categories/', include('categories.urls', namespace="categories")),
    path('sources/',  include('sources.urls', namespace="sources")),
    path('users/',  include('users.urls', namespace="users")),
    path('csvs/',  include('csvs.urls', namespace="csvs")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

categories/models.py
from django.db import models

# Create your models here.

class Category (models.Model):
   
    category = models.CharField(unique=True, max_length=30)
    
    def __str__(self):
        return self.category

categories/forms.py
from django import forms
from django.forms import ModelForm
from .models import Category

class CategoryModelForm(forms.ModelForm):
  class Meta:
    model = Category
    fields = (
        'category',
    )

categories/views.py
from django.shortcuts import render, reverse, redirect
from django.views import generic
from .forms import CategoryModelForm
from .models import Category
from users.views import staff


class CategoryCreateView(staff, generic.CreateView):
    model = Category
    template_name = "categories/category_create.html"
    form_class = CategoryModelForm

    def get_success_url(self):
       return reverse("categories:category-index")

class MixViewCategory(generic.View):
    def get(self, request):
        allcategories = Category.objects.order_by('id')
        form = CategoryModelForm
        context = {
            'categories': allcategories,
            'form': form
        }
        return  render(request, "categories/category_index.html", context)



class CategoryUpdateView(generic.UpdateView):
   model = Category
   template_name = "categories/category_update.html"
   form_class = CategoryModelForm
    
   def get_success_url(self):
     return reverse("categories:category-index")


def category_delete(request, pk):
    category = Category.objects.get(id=pk)
    category.delete()
    return redirect("/categories")

categories/templates/categories/category_create.html
{% extends "base.html" %}
{% load tailwind_filters %}
{{form.media}}
{% block title %}
  create category
{% endblock title %}
{% block content %}
<br>
  <div class="row justify-content-center">
    <div class="col-lg-8 col-md-10 col-sm-12">
      <div class="redbull text-muted text-center">
        <h3 class="card-title">Create a new category. </h3>
        </div>
          <form method="post" novalidate>
            {% csrf_token %}
            {{form|crispy}}
        </div>
      </div>
      <br>
      <div class="text-muted text-center">
        <button type="submit" class="btn btn-primary col-lg-8"><span class="fa fa-hdd" aria-hidden="true"></span> Create</button>
      </form>
      <h1 style="margin-top: 10px;"><a href="/categories"class="btn btn-danger col-lg-8"><span class="fa fa-undo" aria-hidden="true"></span> Back</a></h1>
      </div>
</div>
{% endblock content %}

categories/templates/categories/category_index.html
{%extends 'base.html'%}
{% load tailwind_filters %}
<title>
	{% block title %}
	  categories
	{% endblock title %}
  </title>
  <body>
{%block content%}
<br><br>
<div class="row justify-content-center">
    <div class="col-lg-8 col-md-10 col-sm-12">
      <div class="redbull text-muted text-center">
        <h3 class="card-title">Quick Create a new Category. </h3>
        </div>
          <form action="{% url 'categories:category-create' %}" method="post" novalidate>
            {% csrf_token %}
            {{form|crispy}}
        </div>
      </div>
      <br>
      <div class="text-muted text-center">
        <button type="submit" class="btn btn-primary col-lg-8"><span class="fa fa-hdd" aria-hidden="true"></span> Create</button>
      </form>
      </div>
<br><br>
<table id="categories" class="table table-bordered nowrap table-sm" cellspacing="0" style="width:100%">
    {% csrf_token %}
	<thead class="thead-dark">
		<tr>
			<th class="text-center">#</th>
			<th class="text-center">Category</th>
			<th class="text-center">Action</th>
		</tr>
	</thead>
	<tbody>
		{% for category in categories %}
		<tr id="{{lead.id}}">
			<td class="text-center">{{category.id}}</td>
			<td class="text-center"><a href="{% url 'categories:category-update' category.pk %}">{{category}}</a></td>
			<td class="text-center">
				<a href="{% url 'categories:category-update' category.pk %}"><i class="fas fa-edit text-primary"></i></a>
				<a href="{% url 'categories:category-delete' category.pk %}" onclick="return confirm('Are you sure to delete this Category?');"><i class="fas fa-trash-alt text-danger"></i></a>
			</td>
		</tr>
		{% endfor %}
	</tbody>
</table>
{% if is_paginated %}
<nav aria-label="Page navigation example">
<ul class="pagination justify-content-center pagination-circle">
 {% if page_obj.has_previous %}
  <li class="page-item"><a class="page-link text-secondary" href="?page={{ page_obj.previous_page_number }}"><i class="fas fa-arrow-left text-dark"></i> Previous</a></li>
{% else %}
  <li class="page-item"><a><span class="page-link text-secondary">&laquo;</span></a></li>
{% endif %}
{% for i in paginator.page_range %}
  {% if page_obj.number == i %}
  <li class="active page-item text-secondary"><span class="page-link">{{ i }}</span></li>
  {% else %}
  <li class="page-item"><a class="page-link text-dark" href="?page={{ i }}">{{ i }}</a></li>
  {% endif %}
{% endfor %}
{% if page_obj.has_next %}
  <li class="page-item"><a class="page-link text-secondary" href="?page={{ page_obj.next_page_number }}">Next <i class="fas fa-arrow-right text-dark"></i></a></li>
{% else %}
  <li class="page-item"><span class="page-link text-secondary">&raquo;</span></li>
{% endif %}
</ul>
</nav>
{% endif %}
<br><br>
<script>
    $(document).ready(function(){
        var table = $('#categories').DataTable({
            "paging":true,
            "aLengthMenu":[[10,25,50,100],[10,25,50,100]],
            "iDisplayLength":25,
            "searching":false,
            "responsive":true,
            "order": []
        });
	});
</script>
{%endblock content%}
</body>

categories/templates/categories/category_update.html
{% extends "base.html" %}
{% load tailwind_filters %}
{{form.media}}
{% block title %}
  update {{category}}
{% endblock title %}
{% block content %}
<br>
  <div class="row justify-content-center">
    <div class="col-lg-8 col-md-10 col-sm-12">
      <div class="redbull text-muted text-center">
        <h3 class="card-title">Update category {{category}}. </h3>
        </div>
          <form method="post" novalidate>
            {% csrf_token %}
            {{form|crispy}}
        </div>
      </div>
      <br>
      <div class="text-muted text-center">
        <button type="submit" class="btn btn-primary col-lg-8"><span class="fa fa-hdd" aria-hidden="true"></span> Update</button>
      </form>
      <h1 style="margin-top: 10px;"><a href="/categories"class="btn btn-danger col-lg-8"><span class="fa fa-undo" aria-hidden="true"></span> Back</a></h1>
      </div>
</div>
{% endblock content %}